apiVersion: v1
kind: Service
metadata:
  name: melichallenge-load-balancer
  namespace: app-melichallenge
spec:
  # loadBalancerIP: 52.151.217.51
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: melichallenge